services:
  hydra-server:
    env_file: .env
    image: hydra-server:latest
    restart: unless-stopped
    ports: [ "32001:3001" ]

  hydra-client:
    image: hydra-client:latest
    env_file: .env
    container_name: hydra-client
    restart: unless-stopped
    ports: [ "32000:80" ]
    depends_on: [ hydra-server ]
