services:
  hydra-server:
    env_file: .env
    image: hydra-server:latest
    restart: unless-stopped
    ports: [ "32001:3001" ]

  hydra-client:
    image: hydra-client:latest
    env_file: .env
    container_name: hydra-client
    restart: unless-stopped
    ports: [ "32000:80" ]
    depends_on: [ hydra-server ]

  dex:
    image: hydra-idp:latest
    restart: unless-stopped
    ports: [ "5556:5556","5557:5557" ]

  keycloak:
    image: hydra-iam:latest
    env_file: .env
    restart: unless-stopped
    ports: [ "38080:8080" ]



